trigger:
- none

pool:
  name: lab
  
steps:
- task: Ansible@0
  inputs:
    ansibleInterface: 'remoteMachine'
    connectionOverSsh: 'ansible'
    playbookSourceRemoteMachine: 'ansibleMachine'
    playbookPathAnsibleMachineOnRemoteMachine: 'ansible/test.yaml'
    inventoriesRemoteMachine: 'file'
    inventoryFileSourceRemoteMachine: 'ansibleMachine'
    inventoryFileAnsibleMachineOnRemoteMachine: 'ansible/inventory/hosts'