trigger:
- none

pool:
  vmImage: ubuntu-latest
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'cp -r kubernetes/cluster /home/automation'
    workingDirectory: '$(Build.SourcesDirectory)'
- task: Ansible@0
  inputs:
    ansibleInterface: 'remoteMachine'
    connectionOverSsh: 'ansible'
    playbookSourceRemoteMachine: 'ansibleMachine'
    playbookPathAnsibleMachineOnRemoteMachine: 'ansible/test.yaml'
    inventoriesRemoteMachine: 'file'
    inventoryFileSourceRemoteMachine: 'ansibleMachine'
    inventoryFileAnsibleMachineOnRemoteMachine: 'ansible/inventory/hosts'