trigger:
- none

pool:
  name: lab
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'cp -r kubernetes/cluster /home/automation'
    workingDirectory: '$(Build.SourcesDirectory)'
- task: Ansible@0
  inputs:
    ansibleInterface: 'remoteMachine'
    connectionOverSsh: 'ansible'
    playbookSourceRemoteMachine: 'agentMachine''
    playbookPathAnsibleMachineOnRemoteMachine: 'ansible/test.yaml'
    playbookRootRemoteMachine: '$(Build.SourcesDirectory)'
    inventoryFileSourceRemoteMachine: 'agentMachine'
    inventoryFileLinkedArtifactOnRemoteMachine: 'kubernetes/inventory/hosts'