trigger:
- none
variables:
- group: Ansible

pool:
  name: lab
  
steps:
- task: Ansible@0
  inputs:
    ansibleInterface: 'remoteMachine'
    connectionOverSsh: 'ansible'
    playbookSourceRemoteMachine: 'agentMachine'
    playbookRootRemoteMachine: '$(Build.SourcesDirectory)'
    playbookPathLinkedArtifactOnRemoteMachine: 'kubernetes/kubernetes.yaml'
    inventoriesRemoteMachine: 'file'
    inventoryFileSourceRemoteMachine: 'agentMachine'
    inventoryFileLinkedArtifactOnRemoteMachine: 'kubernetes/inventory/hosts'
    args: --extra-vars '{"password":"$(kube.password)", "build_dir":"$(Build.SourcesDirectory)"}'