---
- name: Test
  hosts: all

  tasks:
  - name: Install vim
    ansible.builtin.dnf:
      name: vim
      state: latest

  - name: Add moules to nodes
    ansible.builtin.copy:
      dest: /etc/modules-load.d/k8s.conf
      content: |
        overlay
        br_netfilter
      owner: root
      group: root
      mode: '0644'

  - name: Config kernel moules
    ansible.builtin.copy:
      dest: sudo vim /etc/sysctl.d/k8s.conf
      content: |
        net.bridge.bridge-nf-call-iptables = 1
        net.ipv4.ip_forward = 1
        net.bridge.bridge-nf-call-ip6tables = 1
      owner: root
      group: root
      mode: '0644'

  - name: Reload parameters
    ansible.builtin.shell:
      cmd: sysctl --system 

  - name: Install yum-utils
    ansible.builtin.shell:
      cmd: yum install -y yum-utils

  - name: Add repository
    ansible.builtin.shell:
      cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install containerd
    ansible.builtin.shell:
      cmd: dnf install containerd.io -y

  - name: Make beckup config.toml
    ansible.builtin.copy:
      src: /etc/containerd/config.toml
      dest: /etc/containerd/config.toml.bkp

    